---
galaxy_info:
    author: Liam Decareaux
    description: base hardening
    license: MIT
    min_ansible_version: "2.15"
    platforms:
        - name: Debian
          versions:
              - trixie
dependencies: []
